-- recovery_progress table stores completed tasks for each session
create table public.recovery_progress (
  id bigint generated by default as identity primary key,
  session_id text not null,
  task_id text not null,
  created_at timestamp with time zone default now() not null,
  unique (session_id, task_id)
);

-- Disable Row Level Security (RLS) as requested.
-- This allows anyone with your anon key to read/write to this table.
-- Be sure you understand the security implications.
alter table public.recovery_progress disable row level security;
